### ISSUE TITLE
yo react-gen error

### ISSUE THREAD

**Issue by zanjs** [fullstackreact/react-gen-generator#6]
```
➜  reactjs yo react-gen

     _-----_
    |       |    .--------------------------.
    |--(o)--|    |   Welcome to the gnarly  |
   `---------´   |    generator-react-gen   |
    ( _´U`_ )    |        generator!        |
    /___A___\    '--------------------------'
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? App name react-gen
? Author name Julian
? Author email zanjser@163.com

events.js:160
      throw er; // Unhandled 'error' event
      ^
AssertionError: Trying to copy from a source that does not exist: /Users/julaud/.nvm/versions/node/v6.2.0/lib/node_modules/generator-react-gen/generators/app/templates/.env
    at EditionInterface.exports._copySingle (/Users/julaud/.nvm/versions/node/v6.2.0/lib/node_modules/generator-react-gen/node_modules/mem-fs-editor/lib/actions/copy.js:45:3)
    at EditionInterface.exports.copy (/Users/julaud/.nvm/versions/node/v6.2.0/lib/node_modules/generator-react-gen/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl] (/Users/julaud/.nvm/versions/node/v6.2.0/lib/node_modules/generator-react-gen/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:10:8)
    at tplCopy (/Users/julaud/.nvm/versions/node/v6.2.0/lib/node_modules/generator-react-gen/generators/app/index.js:7:11)
    at files.forEach.filename (/Users/julaud/.nvm/versions/node/v6.2.0/lib/node_modules/generator-react-gen/generators/app/index.js:17:5)
    at Array.forEach (native)
    at fileListCopy (/%   
```

**Comment by alvarosaavedra** [comment]
https://github.com/fullstackreact/react-gen-generator/issues/1 check this solution worked for me

**Comment by auser** [comment]
Latest push fixes this bug.
